### ISSUE TITLE
Crypto Example display issue...

### ISSUE THREAD

**Issue by SalvorinFex** [luna/luna-studio#805]
After running the Crypto example on my Mac I noticed that this screenshot shows a problem in Windows.
It just displays the text of the dollar amount instead of the nice graph.

Is there something else I need to do to get the graph?

![luna crypto error3](https://user-images.githubusercontent.com/2433369/35885931-4e08fa5c-0b44-11e8-94a8-603e5d456931.png)

**Comment by kustosz** [comment]
Yes! The little triangle next to the value is the visualization chooser. Select `echarts: plot` and you're good. Every value in Luna can be visualized in many different ways, so that menu is there to manage it.

**Comment by kustosz** [comment]
Though yes, there's an issue on Windows with the default visualizer chosen – on mac and linux it's the plot, on Windows that does not work well. Assigning @ljkania for investigation.

**Comment by SalvorinFex** [comment]
I am not getting that option, please see below;

![screenshot 2018-02-06 21 20 37_cr](https://user-images.githubusercontent.com/2433369/35899868-c4026d94-0b83-11e8-8277-0f2923eb4815.jpg)

**Comment by kustosz** [comment]
Oh. Was there any error on the node before? Have you tried double clicking the background to go level up and then double clicking the `main` node again to recompute everything? That sometimes help.

@ljkania this is the issue I run into one day and was telling you about.

**Comment by SalvorinFex** [comment]
Okay,  I just tried that and see the same thing.

**Comment by SalvorinFex** [comment]
Hello folks, I was just following up after a couple of days, to find out what might be happening here.

**Comment by SalvorinFex** [comment]
Hello again, This has been here for a week now, without any additional input from you.
If this is a known issue, is there any sort of workaround?

**Comment by ljkania** [comment]
Hi! I am terribly sorry. I got stuck with another task. I have a really hard time to reproduce it. Will update you soon!

**Comment by ljkania** [comment]
Hello there again! This issue will become outdated when our new approach to visualisations is finally merged into master. Next public version should get rid of this problem, so stay tuned! :)

**Comment by SalvorinFex** [comment]
Staying tuned but no new news yet.

**Comment by kustosz** [comment]
@SalvorinFex 1.2 is coming out on tuesday and should fix the issue. There will also most probably be a nightly tomorrow with the same changes, I'll let you know.

**Comment by kustosz** [comment]
@SalvorinFex OK, there's a version that should fix it now, though still hidden. I'd like to ask you to check if the issue persists there.
1. Please run the Luna Installer.
2. Press Ctrl+D – a message saying "Developer builds are shown" should pop up.
3. Select and install the 1.1.0.1 version
Please let me know if this new version fixes this issue for you.

**Comment by SalvorinFex** [comment]
@kustosz I just installed 1.2 beta and the issue is still there.
I only shows the numbers instead of the graph.

**Comment by SalvorinFex** [comment]
@kustosz Hey there, any word on this continuing issue?

**Comment by kustosz** [comment]
@SalvorinFex: @ljkania will have look at this again tomorrow. Just one question for now – what options are there in the menu in `1.2`? `base: error` isn't a thing in this version anymore, so it would be helpful to know what is there now.

**Comment by SalvorinFex** [comment]
![screenshot 2018-02-25 18 23 32_cr](https://user-images.githubusercontent.com/2433369/36650591-288dab0a-1a59-11e8-8821-da69d05ae636.jpg)

**Comment by ljkania** [comment]
But this looks fine. Just select `echarts: plot` type of visualization. The only problem is that in this particular example it should be selected as default. Could you provide `.lunaproject` file and logs from `luna-empire`?

**Comment by SalvorinFex** [comment]
Can you please let me know where to find those requested files?

**Comment by ljkania** [comment]
`CryptoCurrencyPlayground.lunaproject` file is in the root folder of your project - you can see it in tree view at first screenshot. Logs should be in path: `ProgramFiles\LunaStudio\current\config\logs\luna-empire.stdout.log` or something similar to this. I don't have Windows machine with me so it can differ a little.

**Comment by SalvorinFex** [comment]
[logs.zip](https://github.com/luna/luna-studio/files/1760658/logs.zip)

[CryptoCurrencyPlayground.zip](https://github.com/luna/luna-studio/files/1760664/CryptoCurrencyPlayground.zip)

**Comment by ljkania** [comment]
I have no idea what went wrong after seeing your files. Please, give me few days to investigate it. I will update you until the end of the week.

**Comment by ljkania** [comment]
@SalvorinFex I've just merged pr which should finally fix this problem. Stay tune for the next version :)
